/* 
 * © 2020 Edwin Jose Palathinkal
 */
/**
 * Author:  edwin
 * Created: May 17, 2020
 */

DROP TABLE IF EXISTS HOUSEHOLDS;
CREATE TABLE IF NOT EXISTS HOUSEHOLDS (
  ID IDENTITY,
  TYPE VARCHAR_IGNORECASE(256) NOT NULL CHECK TYPE IN ('Landed', 'Condominium', 'HDB')
);

DROP TABLE IF EXISTS FAMILY_MEMBERS;
CREATE TABLE IF NOT EXISTS FAMILY_MEMBERS (
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR_IGNORECASE(256) NOT NULL,
  GENDER VARCHAR_IGNORECASE(256) NOT NULL CHECK GENDER IN('MALE', 'FEMALE', 'OTHER'),
  MARITAL_STATUS VARCHAR_IGNORECASE(256) NOT NULL CHECK MARITAL_STATUS IN('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED'),
  SPOUSE_ID BIGINT UNIQUE,
  FOREIGN KEY(SPOUSE_ID) REFERENCES FAMILY_MEMBERS(ID),
  OCCUPATION_TYPE VARCHAR_IGNORECASE(256) NOT NULL CHECK OCCUPATION_TYPE IN('Unemployed', 'Student', 'Employed'),
  ANNUAL_INCOME INT CHECK ANNUAL_INCOME >= 0,
  DOB DATE NOT NULL,
  HOUSEHOLD_ID BIGINT NOT NULL,
  FOREIGN KEY(HOUSEHOLD_ID) REFERENCES HOUSEHOLDS(ID)
);